export default [
    { label: 'black', style: 'black' },
    { label: 'gray', style: 'gray' },
    { label: 'darkgray', style: 'darkgray' },
    { label: 'lightgray', style: 'lightgray' },
    { label: 'whitesmoke', style: 'whitesmoke' },
    { label: 'darkred', style: 'darkred' },
    { label: 'firebrick', style: 'firebrick' },
    { label: 'red', style: 'red' },
    { label: 'lightcoral', style: 'lightcoral' },
    { label: 'lightpink', style: 'lightpink'},
    { label: 'orangered', style: 'orangered' },
    { label: 'darkorange', style: 'darkorange' },
    { label: 'orange', style: 'orange' },
    { label: 'lightsalmon', style: 'lightsalmon' },
    { label: 'peachpuff', style: 'peachpuff' },
    { label: 'goldenrod', style: 'goldenrod' },
    { label: 'gold', style: 'gold' },    
    { label: 'yellow', style: 'yellow' },
    { label: 'khaki', style: 'khaki' },
    { label: 'palegoldenrod', style: 'palegoldenrod' },
    { label: 'darkgreen', style: 'darkgreen' },
    { label: 'green', style: 'green' },
    { label: 'forestgreen', style: 'forestgreen' },
    { label: 'seagreen', style: 'seagreen' },
    { label: 'mediumseagreen', style: 'mediumseagreen' },
	{ label: 'darkblue', style: 'darkblue' },
	{ label: 'mediumblue', style: 'mediumblue' },
	{ label: 'blue', style: 'blue' },
	{ label: 'royalblue', style: 'royalblue' },    
	{ label: 'cornflowerblue', style: 'cornflowerblue' },
    { label: 'purple', style: 'purple' },
    { label: 'darkorchid', style: 'darkorchid' },
    { label: 'orchid', style: 'orchid' },
	{ label: 'violet', style: 'violet' },
	{ label: 'plum', style: 'plum' },
];
