export default [ 
    {label: '8', style: 'FONT_SIZE_8'},
    {label: '9', style: 'FONT_SIZE_9'},
    {label: '10', style: 'FONT_SIZE_10'},
    {label: '11', style: 'FONT_SIZE_11'},
    {label: '12', style: 'FONT_SIZE_12'},
    {label: '14', style: 'FONT_SIZE_14'},
    {label: '18', style: 'FONT_SIZE_18'},
    {label: '24', style: 'FONT_SIZE_24'},
    {label: '30', style: 'FONT_SIZE_30'},
    {label: '36', style: 'FONT_SIZE_36'},
    {label: '48', style: 'FONT_SIZE_48'},
    {label: '60', style: 'FONT_SIZE_60'},
    {label: '72', style: 'FONT_SIZE_72'},
    {label: '96', style: 'FONT_SIZE_96'},
     ];